#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1

BIN=/usr/bin/python3 

start_service() {
    procd_open_instance
    procd_set_param command $BIN /root/bot.py
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-10} ${respawn_retry:-10}
    procd_set_param stdout 1
    procd_set_param stderr 1 
    procd_close_instance
}
